import { FileText, Stethoscope, Beaker, ChevronRight } from 'lucide-react';
import { mockPatientHistory, mockPatientsList } from '../data/mockData';

export default function PatientHistory() {
  const patient = mockPatientsList[0];

  const getIcon = (type: string) => {
    switch (type) {
      case 'visit': return <Stethoscope className="h-5 w-5" />;
      case 'lab': return <Beaker className="h-5 w-5" />;
      default: return <FileText className="h-5 w-5" />;
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Patient History</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Viewing records for <span className="font-medium text-foreground">{patient.name}</span> ({patient.age}y, {patient.gender})
          </p>
        </div>
        <button className="bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 rounded-md font-medium text-sm transition-colors">
          Download Full Report
        </button>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* Timeline */}
        <div className="rounded-xl border bg-card text-card-foreground shadow-sm p-6">
          <h3 className="font-semibold leading-none tracking-tight mb-6 text-xl">Treatment Timeline</h3>
          <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-border before:to-transparent">
            {mockPatientHistory.map((item, index) => (
              <div key={item.id} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 border-card bg-primary text-primary-foreground shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10">
                  {getIcon(item.type)}
                </div>
                <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-xl border bg-muted/50 hover:bg-muted transition-colors shadow-sm">
                  <div className="flex items-center justify-between mb-1">
                    <h4 className="font-bold text-foreground">{item.title}</h4>
                    <time className="text-xs font-medium text-muted-foreground">{new Date(item.date).toLocaleDateString()}</time>
                  </div>
                  <p className="text-sm text-muted-foreground">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Diagnostic Reports */}
        <div className="rounded-xl border bg-card text-card-foreground shadow-sm p-6 flex flex-col">
          <h3 className="font-semibold leading-none tracking-tight mb-6 text-xl">Recent Diagnostic Reports</h3>
          <div className="space-y-4 flex-1">
            {[1, 2, 3].map((i) => (
              <div key={i} className="group flex items-center p-4 border rounded-lg hover:border-primary/50 hover:shadow-sm transition-all cursor-pointer">
                <div className="p-3 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg mr-4">
                  <FileText className="h-6 w-6" />
                </div>
                <div className="flex-1">
                  <h4 className="text-sm font-semibold text-foreground group-hover:text-primary transition-colors">Complete Blood Count (CBC)</h4>
                  <p className="text-xs text-muted-foreground mt-1">Generated by Dr. Smith on {new Date().toLocaleDateString()}</p>
                </div>
                <ChevronRight className="h-5 w-5 text-muted-foreground group-hover:text-primary transition-colors" />
              </div>
            ))}
          </div>
          <div className="mt-6 pt-4 border-t text-center">
            <button className="text-sm font-medium text-primary hover:underline">View All Documents</button>
          </div>
        </div>
      </div>
    </div>
  );
}
